SELECT
AGING_PERIOD_LINE_ID,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
CREATED_BY,
CREATION_DATE,
AGING_PERIOD_ID,
PERIOD_SEQUENCE_NUM,
DAYS_START,
DAYS_TO,
TYPE,
REPORT_HEADING1,
REPORT_HEADING2,
REPORT_HEADING3,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
LAST_UPDATE_LOGIN,
OBJECT_VERSION_NUMBER,
SEED_DATA_SOURCE
from (SELECT
AGING_PERIOD_LINE_ID,
LAST_UPDATED_BY,
TO_CHAR(LAST_UPDATE_DATE,'MM-DD-YYYY HH24:MI:SS') LAST_UPDATE_DATE,
CREATED_BY,
TO_CHAR(CREATION_DATE,'MM-DD-YYYY HH24:MI:SS') CREATION_DATE,
AGING_PERIOD_ID,
PERIOD_SEQUENCE_NUM,
DAYS_START,
DAYS_TO,
TYPE,
REPORT_HEADING1,
REPORT_HEADING2,
REPORT_HEADING3,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
ATTRIBUTE11,
ATTRIBUTE12,
ATTRIBUTE13,
ATTRIBUTE14,
ATTRIBUTE15,
LAST_UPDATE_LOGIN,
OBJECT_VERSION_NUMBER,
SEED_DATA_SOURCE,
ROW_NUMBER() OVER(ORDER BY ROWID) AS ROW_NUM
FROM AP_AGING_PERIOD_LINES
WHERE LAST_UPDATE_DATE >=:DeltaBeginTime 
AND LAST_UPDATE_DATE   <=:DeltaEndTime 
UNION ALL 
SELECT 
-1 AGING_PERIOD_LINE_ID,
'X' LAST_UPDATED_BY,
TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS') LAST_UPDATE_DATE,
'X' CREATED_BY,
TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS') CREATION_DATE,
-1 AGING_PERIOD_ID,
-1 PERIOD_SEQUENCE_NUM,
-1 DAYS_START,
-1 DAYS_TO,
'X' TYPE,
'X' REPORT_HEADING1,
'X' REPORT_HEADING2,
'X' REPORT_HEADING3,
'X' ATTRIBUTE_CATEGORY,
'X' ATTRIBUTE1,
'X' ATTRIBUTE2,
'X' ATTRIBUTE3,
'X' ATTRIBUTE4,
'X' ATTRIBUTE5,
'X' ATTRIBUTE6,
'X' ATTRIBUTE7,
'X' ATTRIBUTE8,
'X' ATTRIBUTE9,
'X' ATTRIBUTE10,
'X' ATTRIBUTE11,
'X' ATTRIBUTE12,
'X' ATTRIBUTE13,
'X' ATTRIBUTE14,
'X' ATTRIBUTE15,
'X' LAST_UPDATE_LOGIN,
-1 OBJECT_VERSION_NUMBER,
'X' SEED_DATA_SOURCE,
0 ROW_NUM
FROM DUAL )
WHERE ROW_NUM=0 OR (ROW_NUM >= :RnStartValue AND ROW_NUM < :RnEndValue)



















