SELECT
CODE_COMBINATION_ID
, LAST_UPDATE_DATE
, LAST_UPDATED_BY
, CHART_OF_ACCOUNTS_ID
, DETAIL_POSTING_ALLOWED_FLAG
, DETAIL_BUDGETING_ALLOWED_FLAG
, ACCOUNT_TYPE
, ENABLED_FLAG
, SUMMARY_FLAG
, SEGMENT1
, SEGMENT2
, SEGMENT3
, SEGMENT4
, SEGMENT5
, SEGMENT6
, SEGMENT7
, SEGMENT8
, SEGMENT9
, SEGMENT10
, SEGMENT11
, SEGMENT12
, SEGMENT13
, SEGMENT14
, SEGMENT15
, SEGMENT16
, SEGMENT17
, SEGMENT18
, SEGMENT19
, SEGMENT20
, SEGMENT21
, SEGMENT22
, SEGMENT23
, SEGMENT24
, SEGMENT25
, SEGMENT26
, SEGMENT27
, SEGMENT28
, SEGMENT29
, SEGMENT30
, DESCRIPTION
, TEMPLATE_ID
, ALLOCATION_CREATE_FLAG
, START_DATE_ACTIVE
, END_DATE_ACTIVE
, ATTRIBUTE1
, ATTRIBUTE2
, ATTRIBUTE3
, ATTRIBUTE4
, ATTRIBUTE5
, ATTRIBUTE6
, ATTRIBUTE7
, ATTRIBUTE8
, ATTRIBUTE9
, ATTRIBUTE10
, ATTRIBUTE_DATE1
, ATTRIBUTE_DATE2
, ATTRIBUTE_DATE3
, ATTRIBUTE_DATE4
, ATTRIBUTE_DATE5
, ATTRIBUTE_NUMBER1
, ATTRIBUTE_NUMBER2
, ATTRIBUTE_NUMBER3
, ATTRIBUTE_NUMBER4
, ATTRIBUTE_NUMBER5
, ATTRIBUTE_CATEGORY
, SEGMENT_ATTRIBUTE1
, SEGMENT_ATTRIBUTE2
, SEGMENT_ATTRIBUTE3
, SEGMENT_ATTRIBUTE4
, SEGMENT_ATTRIBUTE5
, SEGMENT_ATTRIBUTE6
, SEGMENT_ATTRIBUTE7
, SEGMENT_ATTRIBUTE8
, SEGMENT_ATTRIBUTE9
, SEGMENT_ATTRIBUTE10
, SEGMENT_ATTRIBUTE11
, SEGMENT_ATTRIBUTE12
, SEGMENT_ATTRIBUTE13
, SEGMENT_ATTRIBUTE14
, SEGMENT_ATTRIBUTE15
, SEGMENT_ATTRIBUTE16
, SEGMENT_ATTRIBUTE17
, SEGMENT_ATTRIBUTE18
, SEGMENT_ATTRIBUTE19
, SEGMENT_ATTRIBUTE20
, SEGMENT_ATTRIBUTE21
, SEGMENT_ATTRIBUTE22
, SEGMENT_ATTRIBUTE23
, SEGMENT_ATTRIBUTE24
, SEGMENT_ATTRIBUTE25
, SEGMENT_ATTRIBUTE26
, SEGMENT_ATTRIBUTE27
, SEGMENT_ATTRIBUTE28
, SEGMENT_ATTRIBUTE29
, SEGMENT_ATTRIBUTE30
, SEGMENT_ATTRIBUTE31
, SEGMENT_ATTRIBUTE32
, SEGMENT_ATTRIBUTE33
, SEGMENT_ATTRIBUTE34
, SEGMENT_ATTRIBUTE35
, SEGMENT_ATTRIBUTE36
, SEGMENT_ATTRIBUTE37
, SEGMENT_ATTRIBUTE38
, SEGMENT_ATTRIBUTE39
, SEGMENT_ATTRIBUTE40
, SEGMENT_ATTRIBUTE41
, SEGMENT_ATTRIBUTE42
, JGZZ_RECON_FLAG
, JGZZ_RECON_CONTEXT
, REFERENCE1
, REFERENCE2
, REFERENCE3
, REFERENCE4
, REFERENCE5
, PRESERVE_FLAG
, REFRESH_FLAG
, IGI_BALANCED_BUDGET_FLAG
, COMPANY_COST_CENTER_ORG_ID
, REVALUATION_ID
, LEDGER_SEGMENT
, LEDGER_TYPE_CODE
, ALTERNATE_CODE_COMBINATION_ID
, FINANCIAL_CATEGORY
, OBJECT_VERSION_NUMBER
, CREATION_DATE
, CREATED_BY
, LAST_UPDATE_LOGIN
, DISABLED_BY_FEATURE_CODE
, CVC_END_DATE
FROM(SELECT
CODE_COMBINATION_ID
, TO_CHAR(LAST_UPDATE_DATE,'MM-DD-YYYY HH24-MI-SS')  LAST_UPDATE_DATE
, LAST_UPDATED_BY
, CHART_OF_ACCOUNTS_ID
, DETAIL_POSTING_ALLOWED_FLAG
, DETAIL_BUDGETING_ALLOWED_FLAG
, ACCOUNT_TYPE
, ENABLED_FLAG
, SUMMARY_FLAG
, SEGMENT1
, SEGMENT2
, SEGMENT3
, SEGMENT4
, SEGMENT5
, SEGMENT6
, SEGMENT7
, SEGMENT8
, SEGMENT9
, SEGMENT10
, SEGMENT11
, SEGMENT12
, SEGMENT13
, SEGMENT14
, SEGMENT15
, SEGMENT16
, SEGMENT17
, SEGMENT18
, SEGMENT19
, SEGMENT20
, SEGMENT21
, SEGMENT22
, SEGMENT23
, SEGMENT24
, SEGMENT25
, SEGMENT26
, SEGMENT27
, SEGMENT28
, SEGMENT29
, SEGMENT30
, DESCRIPTION
, TEMPLATE_ID
, ALLOCATION_CREATE_FLAG
, TO_CHAR(START_DATE_ACTIVE,'MM-DD-YYYY HH24-MI-SS') START_DATE_ACTIVE
, TO_CHAR(END_DATE_ACTIVE,'MM-DD-YYYY HH24-MI-SS') END_DATE_ACTIVE
, ATTRIBUTE1
, ATTRIBUTE2
, ATTRIBUTE3
, ATTRIBUTE4
, ATTRIBUTE5
, ATTRIBUTE6
, ATTRIBUTE7
, ATTRIBUTE8
, ATTRIBUTE9
, ATTRIBUTE10
, TO_CHAR(ATTRIBUTE_DATE1,'MM-DD-YYYY HH24-MI-SS') ATTRIBUTE_DATE1
, TO_CHAR(ATTRIBUTE_DATE2,'MM-DD-YYYY HH24-MI-SS') ATTRIBUTE_DATE2
, TO_CHAR(ATTRIBUTE_DATE3,'MM-DD-YYYY HH24-MI-SS') ATTRIBUTE_DATE3
, TO_CHAR(ATTRIBUTE_DATE4,'MM-DD-YYYY HH24-MI-SS') ATTRIBUTE_DATE4
, TO_CHAR(ATTRIBUTE_DATE5,'MM-DD-YYYY HH24-MI-SS') ATTRIBUTE_DATE5
, ATTRIBUTE_NUMBER1
, ATTRIBUTE_NUMBER2
, ATTRIBUTE_NUMBER3
, ATTRIBUTE_NUMBER4
, ATTRIBUTE_NUMBER5
, ATTRIBUTE_CATEGORY
, SEGMENT_ATTRIBUTE1
, SEGMENT_ATTRIBUTE2
, SEGMENT_ATTRIBUTE3
, SEGMENT_ATTRIBUTE4
, SEGMENT_ATTRIBUTE5
, SEGMENT_ATTRIBUTE6
, SEGMENT_ATTRIBUTE7
, SEGMENT_ATTRIBUTE8
, SEGMENT_ATTRIBUTE9
, SEGMENT_ATTRIBUTE10
, SEGMENT_ATTRIBUTE11
, SEGMENT_ATTRIBUTE12
, SEGMENT_ATTRIBUTE13
, SEGMENT_ATTRIBUTE14
, SEGMENT_ATTRIBUTE15
, SEGMENT_ATTRIBUTE16
, SEGMENT_ATTRIBUTE17
, SEGMENT_ATTRIBUTE18
, SEGMENT_ATTRIBUTE19
, SEGMENT_ATTRIBUTE20
, SEGMENT_ATTRIBUTE21
, SEGMENT_ATTRIBUTE22
, SEGMENT_ATTRIBUTE23
, SEGMENT_ATTRIBUTE24
, SEGMENT_ATTRIBUTE25
, SEGMENT_ATTRIBUTE26
, SEGMENT_ATTRIBUTE27
, SEGMENT_ATTRIBUTE28
, SEGMENT_ATTRIBUTE29
, SEGMENT_ATTRIBUTE30
, SEGMENT_ATTRIBUTE31
, SEGMENT_ATTRIBUTE32
, SEGMENT_ATTRIBUTE33
, SEGMENT_ATTRIBUTE34
, SEGMENT_ATTRIBUTE35
, SEGMENT_ATTRIBUTE36
, SEGMENT_ATTRIBUTE37
, SEGMENT_ATTRIBUTE38
, SEGMENT_ATTRIBUTE39
, SEGMENT_ATTRIBUTE40
, SEGMENT_ATTRIBUTE41
, SEGMENT_ATTRIBUTE42
, JGZZ_RECON_FLAG
, JGZZ_RECON_CONTEXT
, REFERENCE1
, REFERENCE2
, REFERENCE3
, REFERENCE4
, REFERENCE5
, PRESERVE_FLAG
, REFRESH_FLAG
, IGI_BALANCED_BUDGET_FLAG
, COMPANY_COST_CENTER_ORG_ID
, REVALUATION_ID
, LEDGER_SEGMENT
, LEDGER_TYPE_CODE
, ALTERNATE_CODE_COMBINATION_ID
, FINANCIAL_CATEGORY
, OBJECT_VERSION_NUMBER
, TO_CHAR(CREATION_DATE,'MM-DD-YYYY HH24-MI-SS') CREATION_DATE
, CREATED_BY
, LAST_UPDATE_LOGIN
, DISABLED_BY_FEATURE_CODE
, TO_CHAR(CVC_END_DATE,'MM-DD-YYYY HH24-MI-SS') CVC_END_DATE,
ROW_NUMBER() OVER(ORDER BY ROWID) AS ROW_NUM
FROM GL_CODE_COMBINATIONS
WHERE LAST_UPDATE_DATE >=:DeltaBeginTime
AND LAST_UPDATE_DATE   <=:DeltaEndTime
UNION ALL
SELECT
-1	CODE_COMBINATION_ID
, TO_CHAR(SYSDATE,'MM-DD-YYYY HH24-MI-SS')	LAST_UPDATE_DATE
, 'X'	LAST_UPDATED_BY
, -1	CHART_OF_ACCOUNTS_ID
, 'X'	DETAIL_POSTING_ALLOWED_FLAG
, 'X'	DETAIL_BUDGETING_ALLOWED_FLAG
, 'X'	ACCOUNT_TYPE
, 'X'	ENABLED_FLAG
, 'X'	SUMMARY_FLAG
, 'X'	SEGMENT1
, 'X'	SEGMENT2
, 'X'	SEGMENT3
, 'X'	SEGMENT4
, 'X'	SEGMENT5
, 'X'	SEGMENT6
, 'X'	SEGMENT7
, 'X'	SEGMENT8
, 'X'	SEGMENT9
, 'X'	SEGMENT10
, 'X'	SEGMENT11
, 'X'	SEGMENT12
, 'X'	SEGMENT13
, 'X'	SEGMENT14
, 'X'	SEGMENT15
, 'X'	SEGMENT16
, 'X'	SEGMENT17
, 'X'	SEGMENT18
, 'X'	SEGMENT19
, 'X'	SEGMENT20
, 'X'	SEGMENT21
, 'X'	SEGMENT22
, 'X'	SEGMENT23
, 'X'	SEGMENT24
, 'X'	SEGMENT25
, 'X'	SEGMENT26
, 'X'	SEGMENT27
, 'X'	SEGMENT28
, 'X'	SEGMENT29
, 'X'	SEGMENT30
, 'X'	DESCRIPTION
, -1	TEMPLATE_ID
, 'X'	ALLOCATION_CREATE_FLAG
, '01-01-1900 00-00-00'	START_DATE_ACTIVE
, '01-01-1900 00-00-00'	END_DATE_ACTIVE
, 'X'	ATTRIBUTE1
, 'X'	ATTRIBUTE2
, 'X'	ATTRIBUTE3
, 'X'	ATTRIBUTE4
, 'X'	ATTRIBUTE5
, 'X'	ATTRIBUTE6
, 'X'	ATTRIBUTE7
, 'X'	ATTRIBUTE8
, 'X'	ATTRIBUTE9
, 'X'	ATTRIBUTE10
, '01-01-1900 00-00-00'	ATTRIBUTE_DATE1
, '01-01-1900 00-00-00'	ATTRIBUTE_DATE2
, '01-01-1900 00-00-00'	ATTRIBUTE_DATE3
, '01-01-1900 00-00-00'	ATTRIBUTE_DATE4
, '01-01-1900 00-00-00'	ATTRIBUTE_DATE5
, -1	ATTRIBUTE_NUMBER1
, -1	ATTRIBUTE_NUMBER2
, -1	ATTRIBUTE_NUMBER3
, -1	ATTRIBUTE_NUMBER4
, -1	ATTRIBUTE_NUMBER5
, 'X'	ATTRIBUTE_CATEGORY
, 'X'	SEGMENT_ATTRIBUTE1
, 'X'	SEGMENT_ATTRIBUTE2
, 'X'	SEGMENT_ATTRIBUTE3
, 'X'	SEGMENT_ATTRIBUTE4
, 'X'	SEGMENT_ATTRIBUTE5
, 'X'	SEGMENT_ATTRIBUTE6
, 'X'	SEGMENT_ATTRIBUTE7
, 'X'	SEGMENT_ATTRIBUTE8
, 'X'	SEGMENT_ATTRIBUTE9
, 'X'	SEGMENT_ATTRIBUTE10
, 'X'	SEGMENT_ATTRIBUTE11
, 'X'	SEGMENT_ATTRIBUTE12
, 'X'	SEGMENT_ATTRIBUTE13
, 'X'	SEGMENT_ATTRIBUTE14
, 'X'	SEGMENT_ATTRIBUTE15
, 'X'	SEGMENT_ATTRIBUTE16
, 'X'	SEGMENT_ATTRIBUTE17
, 'X'	SEGMENT_ATTRIBUTE18
, 'X'	SEGMENT_ATTRIBUTE19
, 'X'	SEGMENT_ATTRIBUTE20
, 'X'	SEGMENT_ATTRIBUTE21
, 'X'	SEGMENT_ATTRIBUTE22
, 'X'	SEGMENT_ATTRIBUTE23
, 'X'	SEGMENT_ATTRIBUTE24
, 'X'	SEGMENT_ATTRIBUTE25
, 'X'	SEGMENT_ATTRIBUTE26
, 'X'	SEGMENT_ATTRIBUTE27
, 'X'	SEGMENT_ATTRIBUTE28
, 'X'	SEGMENT_ATTRIBUTE29
, 'X'	SEGMENT_ATTRIBUTE30
, 'X'	SEGMENT_ATTRIBUTE31
, 'X'	SEGMENT_ATTRIBUTE32
, 'X'	SEGMENT_ATTRIBUTE33
, 'X'	SEGMENT_ATTRIBUTE34
, 'X'	SEGMENT_ATTRIBUTE35
, 'X'	SEGMENT_ATTRIBUTE36
, 'X'	SEGMENT_ATTRIBUTE37
, 'X'	SEGMENT_ATTRIBUTE38
, 'X'	SEGMENT_ATTRIBUTE39
, 'X'	SEGMENT_ATTRIBUTE40
, 'X'	SEGMENT_ATTRIBUTE41
, 'X'	SEGMENT_ATTRIBUTE42
, 'X'	JGZZ_RECON_FLAG
, 'X'	JGZZ_RECON_CONTEXT
, 'X'	REFERENCE1
, 'X'	REFERENCE2
, 'X'	REFERENCE3
, 'X'	REFERENCE4
, 'X'	REFERENCE5
, 'X'	PRESERVE_FLAG
, 'X'	REFRESH_FLAG
, 'X'	IGI_BALANCED_BUDGET_FLAG
, -1	COMPANY_COST_CENTER_ORG_ID
, -1	REVALUATION_ID
, 'X'	LEDGER_SEGMENT
, 'X'	LEDGER_TYPE_CODE
, -1	ALTERNATE_CODE_COMBINATION_ID
, 'X'	FINANCIAL_CATEGORY
, -1	OBJECT_VERSION_NUMBER
, TO_CHAR(SYSDATE,'MM-DD-YYYY HH24-MI-SS')	CREATION_DATE
, 'X'	CREATED_BY
, 'X'	LAST_UPDATE_LOGIN
, 'X'	DISABLED_BY_FEATURE_CODE
, '01-01-1900 00-00-00'	CVC_END_DATE,
0 ROW_NUM
FROM DUAL)
WHERE ROW_NUM=0 OR (ROW_NUM >= :RnStartValue AND ROW_NUM < :RnEndValue)
